colorscheme default

set showcmd
set nu
set expandtab
set tabstop=4
filetype plugin indent on

" Go to the last cursor location when a file is opened, unless this is a
" git commit (in which case it's annoying)
au BufReadPost *
    \ if line("'\"") > 0 && line("'\"") <= line("$") && &filetype != "gitcommit" |
        \ execute("normal `\"") |
    \ endif

inoremap jk <ESC>
let mapleader=" "
set list
set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<
